# baseurl: '/orlyatko'
# permalink: /:title/
# exclude: ['README.md', 'node_modules', 'gulpfile.js', 'package.json', 'CNAME']

baseurl:
permalink: /:title/

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded
