- {
  url : "https://coriolan-ui.github.io",
  title : "Coriolan UI",
  description : "Web development of Coriolan UI site",
  company: "BBQ Agency"
}
- {
  url : "http://codereamertl.com",
  title : "Codereamer",
  description : "Web development of Codereamer Trade Limited site",
  company: "Rooster Studio"
}
- {
  url : "http://nebo.ua",
  title : "Nebo",
  description : "Web development of Nebo Event Management site",
  company: "Rooster Studio"
}
- {
  url : "http://rooooster.com/luckylabs",
  title : "#ЗахватLuckyLabs",
  description : "Web development of Lucky Labs Vatman Man page :)",
  company: "Rooster Studio"
}
- {
  url : "http://mcriviera.com",
  title : "Monte Carlo Riviera",
  description : "Web development of Monte Carlo Riviera site",
  company: "Rooster Studio"
}
- {
  url : "http://skoryk-competition.github.io",
  title : "Skoryk Competition 2016",
  description : "Web development of Skoryk Competition 2016 site",
  company: "Rooster Studio"
}
- {
  url : "http://masteroforion.eu",
  title : "Master Of Orion",
  description : "Web development of Master Of Orion site",
  company: "Persha Studia Wargaming"
}
- {
  url : "http://worldofwarplanes.ru",
  title : "World Of Warplanes",
  description : "Web development of World Of Warplanes site",
  company: "Persha Studia Wargaming"
}
- {
  url : "http://blog.worldofwarplanes.ru",
  title : "World Of Warplanes Blog",
  description : "Web development of World Of Warplanes blog",
  company: "Persha Studia Wargaming"
}
- {
  url : "http://rooooster.com",
  title : "Rooster Studio",
  description : "Web development of Rooster Studio site",
  company: "Rooster Studio"
}
- {
  url : "http://iondigi.com",
  title : "ION Digital",
  description : "Web development of ION Digital site",
  company: "ION Digital"
}
- {
  url : "http://artkb.net",
  title : "ARTKB",
  description : "Web development of ARTKB site",
  company: "ION Digital"
}
- {
  url : "http://qubiostudio.com",
  title : "Qubio Studio",
  description : "Web development of Qubio Studio site",
  company: "ION Digital"
}
- {
  url : "http://motionups.com",
  title : "Motionups",
  description : "Web development of Motionups site",
  company: "ION Digital"
}
- {
  url : "http://tripme.github.io",
  title : "TripMe Apps",
  description : "Web development of TripMe Apps site",
  company: "TripMe Apps"
}
- {
  url : "http://ru.promorepublic.com/university",
  title : "PromoRepublic Blog",
  description : "Web development of PromoRepublic blog",
  company: "PromoRepublic"
}
- {
  url : "http://promorepublic.com",
  title : "PromoRepublic",
  description : "Web development of PromoRepublic site",
  company: "PromoRepublic"
}
- {
  url : "http://irukanji-music.com",
  title : "Irukanji",
  description : "Web development of Irukanji site",
  company: "Rooster Studio"
}
- {
  url : "http://lookinglook.com",
  title : "Lookinglook Records",
  description : "Web development of Lookinglook Records site",
  company: "Rooster Studio"
}
- {
  url : "http://aquadeepmusic.github.io",
  title : "Aqua Deep Music",
  description : "Web development of Aqua Deep Music site",
  company: "Rooster Studio"
}
- {
  url : "http://sentimony.com",
  title : "Sentimony Records",
  description : "Web development of Sentimony Records site",
  company: "Rooster Studio"
}
- {
  url : "http://ihororlovskyi.com",
  title : "Ihor Orlovskyi",
  description : "Web development of Ihor Orlovskyi site",
  company: "Rooster Studio"
}

